services:
  # Azure SQL Edge for local development
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: lego-vibe-db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: LegoVibe123!
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P LegoVibe123! -Q 'SELECT 1' -C"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Next.js app (optional - for full stack development)
  app:
    build: .
    container_name: lego-vibe-app
    environment:
      AZURE_SQL_SERVER: sqlserver
      AZURE_SQL_DATABASE: master
      AZURE_SQL_USERNAME: sa
      AZURE_SQL_PASSWORD: LegoVibe123!
    ports:
      - "3000:3000"
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  sqlserver-data: